# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_auto_20181203_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='_chr',
            new_name='chr',
        ),
    ]
